In [1]:
import tensorflow as tf

In [2]:
a = tf.constant([2])
b = tf.constant([3])

In [3]:
c = a+b
d = b-a

In [4]:
session = tf.Session()

In [5]:
session.run(c)

array([5], dtype=int32)

In [6]:
session.run(d)

array([1], dtype=int32)

In [7]:
session.close()

# Tensors

In [9]:
#Zero dimension
scalar = tf.constant([2])

In [10]:
#One dimension
vector = tf.constant([2,4,7])

In [12]:
#two dimensions
matrix = tf.constant([[1,2,3],[5,6,7],[8,9,10]])

In [13]:
#Three dimensions - Tensor
tensor = tf.constant([ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ])

In [18]:
with tf.Session() as session:
    result = session.run(scalar)
    print(result)
    result = session.run(vector)
    print(result)
    result = session.run(matrix)
    print(result)
    result = session.run(tensor)
    print(result)

[2]
[2 4 7]
[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
[[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


## Matrix addition 

In [19]:
Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])

In [20]:
matadd1 = tf.add(Matrix_one,Matrix_two)
matadd2 = Matrix_one + Matrix_two

In [21]:
with tf.Session() as session:
    result = session.run(matadd1)
    print("Using tensorflow function:")
    print(result)
    result = session.run(matadd2)
    print("Using normal expressions:")
    print(result)

Using tensorflow function:
[[3 4 5]
 [4 5 6]
 [5 6 7]]
Using normal expressions:
[[3 4 5]
 [4 5 6]
 [5 6 7]]


## Matrix product

In [22]:
matmult = tf.matmul(Matrix_one,Matrix_two)

In [25]:
with tf.Session() as session:
    result = session.run(matmult)
    print("Defined using tensorflow function :")
    print(result)

Defined using tensorflow function :
[[12 12 12]
 [18 18 18]
 [24 24 24]]


<a id="ref5"></a>
## Why Tensors?

The Tensor structure helps us by giving the freedom to shape the dataset the way we want.

And it is particularly helpful when dealing with images, due to the nature of how information in images are encoded,

Thinking about images, its easy to understand that it has a height and width, so it would make sense to represent the information contained in it with a two dimensional strucutre (a matrix)... until you remember that images have colors, and to add information about the colors, we need another dimension, and thats when Tensors become particulary helpful.

Images are encoded into color channels, the image data is represented into each color intensity in a color channel at a given point, the most common one being RGB, which means Red, Blue and Green. The information contained into an image is the intensity of each channel color into the width and height of the image, just like this:

<img src='https://ibm.box.com/shared/static/xlpv9h5xws248c09k1rlx7cer69y4grh.png'>
<div style="text-align:center">[[Image Source]](https://msdn.microsoft.com/en-us/library/windows/desktop/dn424131.aspx)</div>

So the intensity of the red channel at each point with width and height can be represented into a matrix, the same goes for the blue and green channels, so we end up having three matrices, and when these are combined they form a tensor. 



# Variables

TensorFlow is a way of representing computation without actually performing it until asked. In this sense, it is a form of lazy computing, and it allows for some great improvements to the running of code:

Faster computation of complex variables

Distributed computation across multiple systems, including GPUs.

Reduced redundency in some computations

In [26]:
x = tf.constant(35)
y = tf.Variable(x + 5)

In [33]:
z = y+10
new = tf.assign(y,z)

In [27]:
model = tf.global_variables_initializer()

In [34]:
with tf.Session() as session:
    session.run(model)
    print(session.run(y))
    print(session.run(new))

40
50


In TensorFlow the differences between constants and variables are that when you declare some constant, it's value can't be changed in the future (also the initialization should be with a value, not with operation).

Nevertheless, when you declare a Variable, you can change it value at the future with tf.assign() method (and the initialization can be with a value or operation).

The function tf.global_variables_initializer() initialises all variables in your code with the value passed as parameter, but it works in async mode, so don't works propertly when exists dependencies between variables.

# Placeholders

A placeholder is simply a variable that we will assign data to at a later date. It allows us to create our operations and build our computation graph, without needing the data. In TensorFlow terminology, we then feed data into the graph through these placeholders.

Placeholders can be seen as "holes" in your model, "holes" which you will pass the data to, you can create them using 
tf.placeholder(datatype), where datatype specifies the type of data (integers, floating points, strings, booleans) along with its precision (8, 16, 32, 64) bits.

In [41]:
x = tf.placeholder(tf.float32)

In [42]:
y = x*2

In [38]:
with tf.Session() as session:
    result = session.run(y, feed_dict={x: [1,2,3]})
    print(result)

[ 2.  4.  6.]


Since data in TensorFlow is passed in form of multidimensional arrays we can pass any kind of tensor through the placeholders to get the answer to the simple multiplication operation:

In [47]:
with tf.Session() as session:
    result = session.run(y,feed_dict={x: [[[1,2,3],[4,5,6]] , [[2,2,2],[3,3,3]]]})
    print(result)

[[[  2.   4.   6.]
  [  8.  10.  12.]]

 [[  4.   4.   4.]
  [  6.   6.   6.]]]


## Operations

An Operation is a node in a TensorFlow Graph that takes zero or more Tensor objects as input, and produces zero or more Tensor objects as output. Objects of type Operation are created by calling a Python op constructor (such as tf.matmul or tf.add) or tf.Graph.create_op.

For example c = tf.matmul(a, b) creates an Operation of type "MatMul" that takes tensors a and b as input, and produces c as output.

In [48]:
a = tf.constant([4])
b = tf.constant([5])

In [49]:
add = tf.add(a,b)
sub = tf.subtract(a,b)
mul = tf.multiply(a,b)

In [50]:
with tf.Session() as session:
    print(session.run(add))
    print(session.run(sub))
    print(session.run(mul))

[9]
[-1]
[20]
